<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="robo_arm"
	xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Constants for robot dimensions -->
	<xacro:property name="PI" value="3.1415926535897931"/>
	<!-- arbitrary value for mass -->
	<xacro:property name="mass" value="1" />
	<!-- Square dimensions (widthxwidth) of beams -->
	<xacro:property name="width" value="0.1" />
	<!-- Link 1 -->
	<xacro:property name="height1" value="2" />
	<!-- Link 2 -->
	<xacro:property name="height2" value="1.2" />
	<!-- Link 3 -->
	<xacro:property name="height3" value="1.2" />
	<!-- Finger -->
	<xacro:property name="height4" value="1" />
	<!-- Size of square 'camera' box -->
	<xacro:property name="camera_link" value="0.05" />
	<!-- Space btw top of beam and the each joint -->
	<xacro:property name="axel_offset" value="0.05" />
	<!-- Import all Gazebo-customization elements, including Gazebo colors -->
	<xacro:include filename="$(find robo_arm_description)/urdf/robo_arm.gazebo" />
	<!-- Import Rviz colors -->
	<xacro:include filename="$(find robo_arm_description)/urdf/materials.xacro" />
	<!-- Used for fixing robot to Gazebo 'base_link' -->
	<link name="world"/>
	<joint name="joint_body" type="continuous">
		<parent link="world"/>
		<child link="link1"/>
		<origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
		<axis xyz="0 0 1"/>
		<dynamics damping="0.9"/>
	</joint>
	<!-- Base Link -->
	<link name="link1">
		<collision>
			<origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${width} ${width} ${height1}"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${width} ${width} ${height1}"/>
			</geometry>
			<material name="orange"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
			<mass value="0.01"/>
			<inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
		</inertial>
	</link>
	<joint name="joint_shoulder" type="continuous">
		<parent link="link1"/>
		<child link="link2"/>
		<origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="0.9"/>
	</joint>
	<!-- Middle Link -->
	<link name="link2">
		<collision>
			<origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
			<geometry>
				<box size="${width} ${width} ${height2}"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
			<geometry>
				<box size="${width} ${width} ${height2}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
			<mass value="0.01"/>
			<inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
		</inertial>
	</link>
	<joint name="joint_elbow" type="continuous">
		<parent link="link2"/>
		<child link="link3"/>
		<origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="0.9"/>
	</joint>
	<!-- Top Link -->
	<link name="link3">
		<collision>
			<origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
			<geometry>
				<box size="${width} ${width} ${height3}"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
			<geometry>
				<box size="${width} ${width} ${height3}"/>
			</geometry>
			<material name="orange"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
			<mass value="0.01"/>
			<inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
		</inertial>
	</link>
	<!-- finger 1-->
	<link name="finger1">
		<collision>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<geometry>
				<box size="${width/4} ${width/4} ${height4/4}"/>
			</geometry>
			<material name="orange"/>
		</collision>
		<visual>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<geometry>
				<box size="${width/4} ${width/4} ${height4/4}"/>
			</geometry>
			<material name="orange"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<mass value="0.01"/>
			<inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
		</inertial>
	</link>
	<joint name="joint_finger1" type="continuous">
		<parent link="link3"/>
		<child link="finger1"/>
		<origin xyz="0 ${-width} ${height2}" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<dynamics damping="0.9"/>
	</joint>
	<!-- finger 2-->
	<link name="finger2">
		<collision>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<geometry>
				<box size="${width/4} ${width/4} ${height4/4}"/>
			</geometry>
			<material name="orange"/>
		</collision>
		<visual>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<geometry>
				<box size="${width/4} ${width/4} ${height4/4}"/>
			</geometry>
			<material name="orange"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<mass value="0.01"/>
			<inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
		</inertial>
	</link>
	<joint name="joint_finger2" type="continuous">
		<parent link="link3"/>
		<child link="finger2"/>
		<origin xyz="0 ${width} ${height2}" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<dynamics damping="0.9"/>
	</joint>
	<!-- finger 3-->
	<link name="finger3">
		<collision>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<geometry>
				<box size="${width/4} ${width/4} ${height4/4}"/>
			</geometry>
			<material name="orange"/>
		</collision>
		<visual>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<geometry>
				<box size="${width/4} ${width/4} ${height4/4}"/>
			</geometry>
			<material name="orange"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<mass value="0.01"/>
			<inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
		</inertial>
	</link>
	<joint name="joint_finger3" type="continuous">
		<parent link="link3"/>
		<child link="finger3"/>
		<origin xyz="${width} 0 ${height2}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="0.9"/>
	</joint>
	<!-- finger 4-->
	<link name="finger4">
		<collision>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<geometry>
				<box size="${width/4} ${width/4} ${height4/4}"/>
			</geometry>
			<material name="orange"/>
		</collision>
		<visual>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<geometry>
				<box size="${width/4} ${width/4} ${height4/4}"/>
			</geometry>
			<material name="orange"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height4/8}" rpy="0 0 0"/>
			<mass value="0.01"/>
			<inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
		</inertial>
	</link>
	<joint name="joint_finger4" type="continuous">
		<parent link="link3"/>
		<child link="finger4"/>
		<origin xyz="${-width} 0 ${height2}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="0.9"/>
	</joint>
	<joint name="camera_joint" type="fixed">
		<axis xyz="0 1 0" />
		<origin xyz="0 0 ${height3 + camera_link*2}" rpy="0 ${-pi/2} 0"/>
		<parent link="link3"/>
		<child link="camera_link"/>
	</joint>
	<!-- Camera -->
	<link name="camera_link">
	</link>
	<!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
	<joint name="camera_optical_joint" type="fixed">
		<!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="camera_link"/>
		<child link="camera_link_optical"/>
	</joint>
	<link name="camera_link_optical"></link>
	<transmission name="tran1">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="joint_body">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor1">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<transmission name="tran2">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="joint_shoulder">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor2">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<transmission name="tran3">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="joint_elbow">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor3">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<transmission name="tran4">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="joint_finger1">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor4">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<transmission name="tran5">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="joint_finger2">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor5">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<transmission name="tran6">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="joint_finger3">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor6">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<transmission name="tran7">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="joint_finger4">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor7">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	
</robot>